ignore locally installed packages when importing
PaulDance/cargo-liner pull request #22
Opened 2024-02-16 15:15 UTC by ToBinio

This PR resolves #21 

Currently, I kept the source origin as a String since I wasn't able to find a list of all possible variants and I didn't want to create an enum with path, registry, and other

I also have overwritten the shorthand for `--with-local` since 'w' feels a bit off

2024-02-16 19:15 UTC, PaulDance requested changes
Hey, thanks for the additional contribution!

A bunch of small things to address, but the core of it is good.

Corresponding integration tests should be added as well. The `tests/import.rs` module includes already includes a few of them. You should therefore be able to relatively easily write the various combinations needed.

2024-02-16 19:15 UTC, PaulDance commented on src/config/cargo_crates_toml.rs
> +                    .collect::<BTreeMap<_, _>>(),
?

2024-02-16 19:15 UTC, PaulDance commented on src/config/cargo_crates_toml.rs
> -                    ("c", "=0.0.0"),
?

2024-02-16 19:15 UTC, PaulDance commented on src/config/cargo_crates_toml.rs
> -                    ("c", "^0.0.0"),
?

2024-02-16 19:15 UTC, PaulDance commented on src/config/cargo_crates_toml.rs
> -                    ("c", "~0.0.0"),
?

2024-02-16 19:15 UTC, PaulDance commented on src/cli.rs
> +    pub with_local: bool,
Just thought about it, but wouldn't it be more consistent with the above option if it was named `keep_local` parsed from `-l/--keep-local` instead? In this case, maybe change the shorthand version of `--keep-self` to `-s`?

2024-02-16 20:18 UTC, ToBinio commented on src/config/cargo_crates_toml.rs
>      }
there now should be test for all 4 cases

2024-02-16 20:21 UTC, ToBinio commented on src/config/cargo_crates_toml.rs
> +                packages: [("a", "*"), ("b", "*")]
```rust
                    (
                        "a",
                        "1.2.3",
                        "registry",
                        "https://example.com/index",
                        vec!["a"],
                    ),
                    (
                        "b",
                        "0.1.2",
                        "registry",
                        "https://example.com/index",
                        vec!["b1", "b2"],
                    ),
                    (
                        "c",
                        "0.0.0",
                        "path",
                        "file:///a/b/c",
                        vec!["c1", "c2", "c3"]
                    ),
                    (
                        "cargo-liner",
                        "0.2.1",
                        "registry",
                        "https://crates.io/index",
                        vec!["cargo-liner"]
                    ),
```

in the test data `c` is a local install so by default it gets excluded

2024-02-17 00:58 UTC, PaulDance requested changes
Thanks for the quick and quality iteration! A few minor things left and we should be good!

2024-02-17 00:58 UTC, PaulDance commented on src/config/cargo_crates_toml.rs
> +    fn into_config<F>(self, pkg_map: F, keep_self: bool, with_local: bool) -> UserConfig
If you could also rename all these `with_local`s to `keep_local`, it would be really nice. `grep -r with_local` to be sure you didn't miss anything.

2024-02-17 00:58 UTC, PaulDance commented on src/config/cargo_crates_toml.rs
> +                packages: [("a", "*"), ("b", "*")]
Oh right, sorry!

2024-02-17 00:58 UTC, PaulDance commented on tests/common/mod.rs
>      )
You should be able to inline `source` here, using `source = ...` as a new argument after the format string in the `writeln!` macro call.

2024-02-17 00:58 UTC, PaulDance commented on src/config/cargo_crates_toml.rs
> +            PackageSource {
```suggestion
            Self {
```

minor

2024-02-17 00:58 UTC, PaulDance commented on tests/fixtures/ship/validate_ship_manynewer_update.stderr
> +warning: be sure to add `[..]/home/.cargo/bin` to your PATH to be able to run the installed binaries
```suggestion
warning: be sure to add `[..]/.cargo/bin` to your PATH to be able to run the installed binaries
```

should be preferable

2024-02-17 00:58 UTC, PaulDance commented on src/config/cargo_crates_toml.rs
>      }
Yes, I saw that and it looked good, thanks!

2024-02-17 18:10 UTC, PaulDance approved these changes
Thanks a bunch!

2024-02-17 18:11 UTC, merged